# Set terminal type
set -g default-terminal "screen-256color"

# Change prefix to C-a (no need to unbind C-b again)
set -g prefix C-a
bind-key C-a send-prefix
bind-key -r C-a send-prefix

# Enable mouse support
set -g mouse on

# Split windows more efficiently
bind '\' split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

# Resize panes with arrow keys
bind -r Down resize-pane -D 15
bind -r Up resize-pane -U 15
bind -r Left resize-pane -L 15
bind -r Right resize-pane -R 15

# Pane selection with vim-like keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Toggle zoom on a pane
bind -r m resize-pane -Z

# Enable vi mode in copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# New window with same directory
bind c new-window -c '#{pane_current_path}'

# Start window index from 1, and renumber when closing windows
set-option -g base-index 1
set-option -g renumber-windows on

# Customize status line
set -g status-right 'Viet Anh 😛'

# Reload tmux config
bind r source-file ~/.tmux.conf
